### PR TITLE
Create a.py

### PR DESCRIPTION
**Pull request by 1acrimosa**

### CODE REVIEW

**Comment by 1acrimosa** [comment]
something

**Comment by Dastan-SDU** [comment]
so, what's up?

**Comment by 1acrimosa** [comment]
nothing
 yet

**Comment by Dastan-SDU** [comment]
do you know what you do?

**Comment by 1acrimosa** [comment]
No, I guess, but it's funny!

**Comment by 1acrimosa** [comment]
> No, I guess, but it's funny!

SOme

**Comment by 1acrimosa** [comment]
> do you know what you do?

nope

**Comment by Dastan-SDU** [comment]
> > do you know what you do?
> 
> nope

>?

**Comment by Dastan-SDU** [comment]
> > No, I guess, but it's funny!
> 
> SOme

a

**Pull request merged**
